### PR TITLE
Added support for custom layout for hint item and dropdown hint item

### PR DESCRIPTION
**Pull request by petecocoon**
Hi, i've added two new options which allow you to use custom view for hint item and drop down hint item.

ms_hintView
ms_dropDownHintView.

### CODE REVIEW

**Comment by petecocoon** [comment]
This PR solve
https://github.com/ganfra/MaterialSpinner/issues/55
https://github.com/ganfra/MaterialSpinner/issues/30
https://github.com/ganfra/MaterialSpinner/issues/19

**Comment by riadhnet** [comment]
ms_hintView
ms_dropDownHintView. doesn't exisit in the version 1.1.1 , 
can you please update it ?

**Comment by RustamG** [comment]
@petecocoon will you push it somewhere to get it via gradle?

**Comment by riadhnet** [comment]
@petecocoon @RustamG 
i took this PR , forked it, updated to target sdk 25 , and made it available to use via gradle 
feel free for any contribution , i did this because we really need this implementation 
https://github.com/riadhnet/MaterialSpinner

**Comment by ganfra** [comment]
Thanks for the work. Sorry for the very long delay

**Pull request merged**
