### PR TITLE
Hint Color Support

### PR DESCRIPTION
**Pull request by matthew-compton**
Added support for changing the hint color, which should fix issue #21.

### CODE REVIEW

**Comment by douglasjunior** [comment]
+1

**Comment by douglasjunior** [comment]
@ganfra Sorry to tagged you. But, this lib is discontinued? I saw that it is stationary since May. There is interest in new features?

**Comment by ganfra** [comment]
Thanks for your PL :)
This lib isn't discontinued, but I don't have much time to work on it ... I'll still try to bring new features regarding of the issues

**Comment by douglasjunior** [comment]
Ok, thanks :smiley:

**Pull request merged**
