### PR TITLE
Three more styleable things: the line thickness, label color and arrow color

### PR DESCRIPTION
**Pull request by rocboronat**
Hi @ganfra !

I just did what I asked you for :·)

Now, people can set the thickness of the line, to meet Material requirements (and also, to be aligned with MaterialEditText). The user can set a colour for the label, too :·)

By the way, there's an issue with the HintAdapter.getViewTypeCount(). I've solved it simply returning it's child method instead of doing a +1 if the hint was set. I didn't want to push it, but I didn't noticed it was an inner class, so I commited it with the line thickness commit.

Hope you think this PR useful! And thanks for your work!

### CODE REVIEW

**Comment by rocboronat** [comment]
Wep, the arrow attribute is interesting, too :·)

**Comment by ganfra** [comment]
Thanks for this ! I'll look into it and then update ... sorry for the long time !

**Comment by rocboronat** [comment]
Don't worry! I'll be working on this for two or three hours more, testing it on our own app (where it's easy to compare with MaterialEditText). So it's not needed to hurry! :-)

**Comment by rocboronat** [comment]
Don't worry! I'll be working on this for two or three hours more, testing it on our own app (where it's easy to compare with MaterialEditText). So it's not needed to hurry! :-)

**Comment by rocboronat** [comment]
(whoops, sorry for double posting!)

**Comment by rocboronat** [comment]
Wep! I'm done! :·)

BTW, only for the information: I think we're misunderstanding the dimens.xml and how are we working with them. I think it's OK to have a default values, and probably dimens.xml is a good place to make it happen. But it could be a good idea to see how MaterialEditText's people is doing it, 'cause I'm pretty sure that they're in the same situation than us, but they did it in a more elegant way.

**Comment by ganfra** [comment]
Thanks for your change :)

**Comment by rocboronat** [comment]
Thanks to you, @ganfra ! Hope I have time to collaborate with you and your library again :·)

**Pull request merged**
